#The confio confio/relayer npm is used by Nois and is developed by confio in this repo https://github.com/confio/ts-relayer.git
#WARN!! This is only for testing the relayers not for production use


FROM DOCKER_IMAGE_TEMPLATE


COPY entrypoint.sh entrypoint.sh
RUN chmod +x entrypoint.sh

ENTRYPOINT ["/entrypoint.sh"]
